name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Import gradle properties
        shell: bash
        run: cat gradle.properties >> $GITHUB_ENV
      - name: Build
        run: ./gradlew build --stacktrace
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Pl3xMap-Claims
          path: build/libs
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          draft: false
          prerelease: false
          title: Pl3xMap-Claims ${{ env.minecraftVersion }}-${{ github.run_number }}
          files: build/libs/*.jar
